# SPDX-License-Identifier: Apache-2.0

name: hello
on: push

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: latest

      - name: Check oc version
        run: |
          oc version
