# SPDX-License-Identifier: Apache-2.0

name: hello
on: push

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: |
          echo 'Hello World!'
          uname -a
          cat /etc/os-release
          df -h
          free -h
          id
          pwd
          env | sort
